[build]
  command = "npm run netlify-build"
  publish = ".output/public"
  environment = { NODE_VERSION = "18.19.0" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/_nuxt/*"
  to = "/_nuxt/:splat"
  status = 200

[[redirects]]
  from = "/wp-content/uploads/*"
  to = "https://shop.therelic.blog/wp-content/uploads/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/wp-content/*"
  to = "https://shop.therelic.blog/wp-content/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"

[[headers]]
  for = "/wp-content/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"

[[headers]]
  for = "/wp-content/uploads/woocommerce-product-images/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"

[[headers]]
  for = "/_ipx/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET"
